# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GuiLib/ColorPickDialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ColorPickDialog(object):
    def setupUi(self, ColorPickDialog):
        ColorPickDialog.setObjectName("ColorPickDialog")
        ColorPickDialog.resize(621, 415)
        self.gridLayout_3 = QtWidgets.QGridLayout(ColorPickDialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_AddColor = QtWidgets.QPushButton(ColorPickDialog)
        self.pushButton_AddColor.setObjectName("pushButton_AddColor")
        self.gridLayout_3.addWidget(self.pushButton_AddColor, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(308, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 4, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(ColorPickDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_3.addWidget(self.buttonBox, 4, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(ColorPickDialog)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_HsvPanel = HsvPanelWidget(ColorPickDialog)
        self.widget_HsvPanel.setObjectName("widget_HsvPanel")
        self.horizontalLayout.addWidget(self.widget_HsvPanel)
        self.widget_Luma = LumaSliderWidget(ColorPickDialog)
        self.widget_Luma.setObjectName("widget_Luma")
        self.splitter = QtWidgets.QSplitter(self.widget_Luma)
        self.splitter.setGeometry(QtCore.QRect(40, 80, 160, 23))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.horizontalLayout.addWidget(self.widget_Luma)
        self.horizontalLayout.setStretch(0, 12)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.spinBox_Val = QtWidgets.QSpinBox(ColorPickDialog)
        self.spinBox_Val.setMaximum(255)
        self.spinBox_Val.setObjectName("spinBox_Val")
        self.gridLayout.addWidget(self.spinBox_Val, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(ColorPickDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.spinBox_Hue = QtWidgets.QSpinBox(ColorPickDialog)
        self.spinBox_Hue.setMaximum(359)
        self.spinBox_Hue.setObjectName("spinBox_Hue")
        self.gridLayout.addWidget(self.spinBox_Hue, 0, 1, 1, 1)
        self.spinBox_Red = QtWidgets.QSpinBox(ColorPickDialog)
        self.spinBox_Red.setMaximum(255)
        self.spinBox_Red.setObjectName("spinBox_Red")
        self.gridLayout.addWidget(self.spinBox_Red, 0, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(ColorPickDialog)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 4, 1, 1)
        self.spinBox_Y = QtWidgets.QSpinBox(ColorPickDialog)
        self.spinBox_Y.setMaximum(255)
        self.spinBox_Y.setObjectName("spinBox_Y")
        self.gridLayout.addWidget(self.spinBox_Y, 0, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(ColorPickDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.spinBox_Sat = QtWidgets.QSpinBox(ColorPickDialog)
        self.spinBox_Sat.setMaximum(255)
        self.spinBox_Sat.setObjectName("spinBox_Sat")
        self.gridLayout.addWidget(self.spinBox_Sat, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(ColorPickDialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(ColorPickDialog)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 4, 1, 1)
        self.spinBox_U = QtWidgets.QSpinBox(ColorPickDialog)
        self.spinBox_U.setMaximum(255)
        self.spinBox_U.setSingleStep(0)
        self.spinBox_U.setObjectName("spinBox_U")
        self.gridLayout.addWidget(self.spinBox_U, 1, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(ColorPickDialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(ColorPickDialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 2, 1, 1)
        self.spinBox_Blue = QtWidgets.QSpinBox(ColorPickDialog)
        self.spinBox_Blue.setMaximum(255)
        self.spinBox_Blue.setObjectName("spinBox_Blue")
        self.gridLayout.addWidget(self.spinBox_Blue, 2, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(ColorPickDialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 4, 1, 1)
        self.spinBox_V = QtWidgets.QSpinBox(ColorPickDialog)
        self.spinBox_V.setMaximum(255)
        self.spinBox_V.setObjectName("spinBox_V")
        self.gridLayout.addWidget(self.spinBox_V, 2, 5, 1, 1)
        self.label_5 = QtWidgets.QLabel(ColorPickDialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(ColorPickDialog)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 0, 1, 1)
        self.lineEdit_Html = QtWidgets.QLineEdit(ColorPickDialog)
        self.lineEdit_Html.setObjectName("lineEdit_Html")
        self.gridLayout.addWidget(self.lineEdit_Html, 3, 1, 1, 3)
        self.spinBox_Green = QtWidgets.QSpinBox(ColorPickDialog)
        self.spinBox_Green.setMaximum(255)
        self.spinBox_Green.setObjectName("spinBox_Green")
        self.gridLayout.addWidget(self.spinBox_Green, 1, 3, 1, 1)
        self.widget_Color = ColorWidget(ColorPickDialog)
        self.widget_Color.setObjectName("widget_Color")
        self.gridLayout.addWidget(self.widget_Color, 3, 5, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout.setStretch(0, 4)
        self.verticalLayout.setStretch(1, 1)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 1, 4, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_Color_6 = ColorWidget(ColorPickDialog)
        self.widget_Color_6.setAutoFillBackground(False)
        self.widget_Color_6.setStyleSheet("Qwidget { background-color: rgb(255, 255, 255) }")
        self.widget_Color_6.setObjectName("widget_Color_6")
        self.gridLayout_2.addWidget(self.widget_Color_6, 1, 4, 1, 1)
        self.widget_Color_2 = ColorWidget(ColorPickDialog)
        self.widget_Color_2.setAutoFillBackground(True)
        self.widget_Color_2.setStyleSheet("Qwidget { background-color: rgb(255, 255, 255) }")
        self.widget_Color_2.setObjectName("widget_Color_2")
        self.gridLayout_2.addWidget(self.widget_Color_2, 1, 0, 1, 1)
        self.widget_Color_4 = ColorWidget(ColorPickDialog)
        self.widget_Color_4.setAutoFillBackground(False)
        self.widget_Color_4.setStyleSheet("Qwidget { background-color: rgb(255, 255, 255) }")
        self.widget_Color_4.setObjectName("widget_Color_4")
        self.gridLayout_2.addWidget(self.widget_Color_4, 1, 2, 1, 1)
        self.widget_Color_16 = ColorWidget(ColorPickDialog)
        self.widget_Color_16.setAutoFillBackground(False)
        self.widget_Color_16.setStyleSheet("Qwidget { background-color: rgb(255, 255, 255) }")
        self.widget_Color_16.setObjectName("widget_Color_16")
        self.gridLayout_2.addWidget(self.widget_Color_16, 0, 3, 1, 1)
        self.widget_Color_3 = ColorWidget(ColorPickDialog)
        self.widget_Color_3.setAutoFillBackground(False)
        self.widget_Color_3.setStyleSheet("Qwidget { background-color: rgb(255, 255, 255) }")
        self.widget_Color_3.setObjectName("widget_Color_3")
        self.gridLayout_2.addWidget(self.widget_Color_3, 1, 1, 1, 1)
        self.widget_Color_9 = ColorWidget(ColorPickDialog)
        self.widget_Color_9.setAutoFillBackground(False)
        self.widget_Color_9.setStyleSheet("Qwidget { background-color: rgb(255, 255, 255) }")
        self.widget_Color_9.setObjectName("widget_Color_9")
        self.gridLayout_2.addWidget(self.widget_Color_9, 1, 7, 1, 1)
        self.widget_Color_14 = ColorWidget(ColorPickDialog)
        self.widget_Color_14.setAutoFillBackground(False)
        self.widget_Color_14.setStyleSheet("Qwidget { background-color: rgb(255, 255, 255) }")
        self.widget_Color_14.setObjectName("widget_Color_14")
        self.gridLayout_2.addWidget(self.widget_Color_14, 0, 5, 1, 1)
        self.widget_Color_10 = ColorWidget(ColorPickDialog)
        self.widget_Color_10.setAutoFillBackground(True)
        self.widget_Color_10.setStyleSheet("Qwidget { background-color: rgb(255, 255, 255) }")
        self.widget_Color_10.setObjectName("widget_Color_10")
        self.gridLayout_2.addWidget(self.widget_Color_10, 0, 0, 1, 1)
        self.widget_Color_12 = ColorWidget(ColorPickDialog)
        self.widget_Color_12.setAutoFillBackground(False)
        self.widget_Color_12.setStyleSheet("Qwidget { background-color: rgb(255, 255, 255) }")
        self.widget_Color_12.setObjectName("widget_Color_12")
        self.gridLayout_2.addWidget(self.widget_Color_12, 0, 2, 1, 1)
        self.widget_Color_5 = ColorWidget(ColorPickDialog)
        self.widget_Color_5.setAutoFillBackground(False)
        self.widget_Color_5.setStyleSheet("Qwidget { background-color: rgb(255, 255, 255) }")
        self.widget_Color_5.setObjectName("widget_Color_5")
        self.gridLayout_2.addWidget(self.widget_Color_5, 1, 3, 1, 1)
        self.widget_Color_7 = ColorWidget(ColorPickDialog)
        self.widget_Color_7.setAutoFillBackground(False)
        self.widget_Color_7.setStyleSheet("Qwidget { background-color: rgb(255, 255, 255) }")
        self.widget_Color_7.setObjectName("widget_Color_7")
        self.gridLayout_2.addWidget(self.widget_Color_7, 1, 5, 1, 1)
        self.widget_Color_17 = ColorWidget(ColorPickDialog)
        self.widget_Color_17.setAutoFillBackground(False)
        self.widget_Color_17.setStyleSheet("Qwidget { background-color: rgb(255, 255, 255) }")
        self.widget_Color_17.setObjectName("widget_Color_17")
        self.gridLayout_2.addWidget(self.widget_Color_17, 0, 6, 1, 1)
        self.widget_Color_13 = ColorWidget(ColorPickDialog)
        self.widget_Color_13.setAutoFillBackground(False)
        self.widget_Color_13.setStyleSheet("Qwidget { background-color: rgb(255, 255, 255) }")
        self.widget_Color_13.setObjectName("widget_Color_13")
        self.gridLayout_2.addWidget(self.widget_Color_13, 0, 7, 1, 1)
        self.widget_Color_8 = ColorWidget(ColorPickDialog)
        self.widget_Color_8.setAutoFillBackground(False)
        self.widget_Color_8.setStyleSheet("Qwidget { background-color: rgb(255, 255, 255) }")
        self.widget_Color_8.setObjectName("widget_Color_8")
        self.gridLayout_2.addWidget(self.widget_Color_8, 1, 6, 1, 1)
        self.widget_Color_11 = ColorWidget(ColorPickDialog)
        self.widget_Color_11.setAutoFillBackground(False)
        self.widget_Color_11.setStyleSheet("Qwidget { background-color: rgb(255, 255, 255) }")
        self.widget_Color_11.setObjectName("widget_Color_11")
        self.gridLayout_2.addWidget(self.widget_Color_11, 0, 4, 1, 1)
        self.widget_Color_15 = ColorWidget(ColorPickDialog)
        self.widget_Color_15.setAutoFillBackground(True)
        self.widget_Color_15.setStyleSheet("Qwidget { background-color: rgb(255, 255, 255) }")
        self.widget_Color_15.setObjectName("widget_Color_15")
        self.gridLayout_2.addWidget(self.widget_Color_15, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 2, 0, 1, 1)

        self.retranslateUi(ColorPickDialog)
        self.buttonBox.accepted.connect(ColorPickDialog.accept)
        self.buttonBox.rejected.connect(ColorPickDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ColorPickDialog)

    def retranslateUi(self, ColorPickDialog):
        _translate = QtCore.QCoreApplication.translate
        ColorPickDialog.setWindowTitle(_translate("ColorPickDialog", "Dialog"))
        self.pushButton_AddColor.setText(_translate("ColorPickDialog", "Add to Custom Colors"))
        self.pushButton.setText(_translate("ColorPickDialog", "Pick Screen Color"))
        self.label_2.setText(_translate("ColorPickDialog", "Hue"))
        self.label_10.setText(_translate("ColorPickDialog", "Y:"))
        self.label_3.setText(_translate("ColorPickDialog", "Sat"))
        self.label_7.setText(_translate("ColorPickDialog", "Green:"))
        self.label_9.setText(_translate("ColorPickDialog", "U:"))
        self.label_4.setText(_translate("ColorPickDialog", "Val"))
        self.label_6.setText(_translate("ColorPickDialog", "Blue:"))
        self.label_8.setText(_translate("ColorPickDialog", "V:"))
        self.label_5.setText(_translate("ColorPickDialog", "Red:"))
        self.label_11.setText(_translate("ColorPickDialog", "HTML:"))

from CustomWidget import ColorWidget, HsvPanelWidget, LumaSliderWidget
