# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GuiLib/ImageSave.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_ImageSave(object):
    def setupUi(self, Dialog_ImageSave):
        Dialog_ImageSave.setObjectName("Dialog_ImageSave")
        Dialog_ImageSave.resize(503, 248)
        self.gridLayout_5 = QtWidgets.QGridLayout(Dialog_ImageSave)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(Dialog_ImageSave)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_BufferInfo = QtWidgets.QGroupBox(self.tab)
        self.groupBox_BufferInfo.setObjectName("groupBox_BufferInfo")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_BufferInfo)
        self.gridLayout.setObjectName("gridLayout")
        self.label_10 = QtWidgets.QLabel(self.groupBox_BufferInfo)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1)
        self.spinBox_BufferP_4 = QtWidgets.QSpinBox(self.groupBox_BufferInfo)
        self.spinBox_BufferP_4.setMaximum(8192)
        self.spinBox_BufferP_4.setProperty("value", 0)
        self.spinBox_BufferP_4.setObjectName("spinBox_BufferP_4")
        self.gridLayout.addWidget(self.spinBox_BufferP_4, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_BufferInfo)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 2, 1, 1)
        self.spinBox_BufferP_5 = QtWidgets.QSpinBox(self.groupBox_BufferInfo)
        self.spinBox_BufferP_5.setMaximum(8192)
        self.spinBox_BufferP_5.setProperty("value", 0)
        self.spinBox_BufferP_5.setObjectName("spinBox_BufferP_5")
        self.gridLayout.addWidget(self.spinBox_BufferP_5, 0, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_BufferInfo)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 4, 1, 1)
        self.spinBox_BufferP_3 = QtWidgets.QSpinBox(self.groupBox_BufferInfo)
        self.spinBox_BufferP_3.setMaximum(8192)
        self.spinBox_BufferP_3.setProperty("value", 1920)
        self.spinBox_BufferP_3.setObjectName("spinBox_BufferP_3")
        self.gridLayout.addWidget(self.spinBox_BufferP_3, 0, 5, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_BufferInfo)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 6, 1, 1)
        self.spinBox_BufferH_3 = QtWidgets.QSpinBox(self.groupBox_BufferInfo)
        self.spinBox_BufferH_3.setMaximum(8192)
        self.spinBox_BufferH_3.setProperty("value", 1080)
        self.spinBox_BufferH_3.setObjectName("spinBox_BufferH_3")
        self.gridLayout.addWidget(self.spinBox_BufferH_3, 0, 7, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_BufferInfo, 0, 0, 1, 4)
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 1, 0, 1, 1)
        self.comboBox_YUVFormat = QtWidgets.QComboBox(self.tab)
        self.comboBox_YUVFormat.setObjectName("comboBox_YUVFormat")
        self.comboBox_YUVFormat.addItem("")
        self.comboBox_YUVFormat.addItem("")
        self.comboBox_YUVFormat.addItem("")
        self.comboBox_YUVFormat.addItem("")
        self.comboBox_YUVFormat.addItem("")
        self.comboBox_YUVFormat.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_YUVFormat, 1, 1, 1, 3)
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 2, 0, 1, 1)
        self.checkBox_YUV = QtWidgets.QCheckBox(self.tab)
        self.checkBox_YUV.setChecked(True)
        self.checkBox_YUV.setObjectName("checkBox_YUV")
        self.gridLayout_4.addWidget(self.checkBox_YUV, 2, 1, 1, 1)
        self.checkBox_Y = QtWidgets.QCheckBox(self.tab)
        self.checkBox_Y.setObjectName("checkBox_Y")
        self.gridLayout_4.addWidget(self.checkBox_Y, 2, 2, 1, 1)
        self.checkBox_UV = QtWidgets.QCheckBox(self.tab)
        self.checkBox_UV.setObjectName("checkBox_UV")
        self.gridLayout_4.addWidget(self.checkBox_UV, 2, 3, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_5.addWidget(self.tabWidget, 0, 0, 1, 2)
        self.label_14 = QtWidgets.QLabel(Dialog_ImageSave)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 1, 0, 1, 1)
        self.lineEdit_FileName = QtWidgets.QLineEdit(Dialog_ImageSave)
        self.lineEdit_FileName.setObjectName("lineEdit_FileName")
        self.gridLayout_5.addWidget(self.lineEdit_FileName, 1, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_ImageSave)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_5.addWidget(self.buttonBox, 2, 1, 1, 1)

        self.retranslateUi(Dialog_ImageSave)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog_ImageSave.accept)
        self.buttonBox.rejected.connect(Dialog_ImageSave.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_ImageSave)

    def retranslateUi(self, Dialog_ImageSave):
        _translate = QtCore.QCoreApplication.translate
        Dialog_ImageSave.setWindowTitle(_translate("Dialog_ImageSave", "Save Image"))
        self.groupBox_BufferInfo.setTitle(_translate("Dialog_ImageSave", "Crop Window"))
        self.label_10.setText(_translate("Dialog_ImageSave", "X:"))
        self.label_11.setText(_translate("Dialog_ImageSave", "X:"))
        self.label_8.setText(_translate("Dialog_ImageSave", "Width"))
        self.label_9.setText(_translate("Dialog_ImageSave", "Height"))
        self.label_12.setText(_translate("Dialog_ImageSave", "Format:"))
        self.comboBox_YUVFormat.setItemText(0, _translate("Dialog_ImageSave", "YUV420_IYUV      YYYY YYYY UU VV"))
        self.comboBox_YUVFormat.setItemText(1, _translate("Dialog_ImageSave", "YUV420_YV12     YYYY YYYY VV UU"))
        self.comboBox_YUVFormat.setItemText(2, _translate("Dialog_ImageSave", "YUV420_NV12     YYYY YYYY UV UV"))
        self.comboBox_YUVFormat.setItemText(3, _translate("Dialog_ImageSave", "YUV422_YU16     YYYY YYYY UUUU VVVV"))
        self.comboBox_YUVFormat.setItemText(4, _translate("Dialog_ImageSave", "YUV422_YV16     YYYY YYYY VVVV UUUU"))
        self.comboBox_YUVFormat.setItemText(5, _translate("Dialog_ImageSave", "YUV422_NV16     YYYY YYYY UVUV UVUV"))
        self.label_13.setText(_translate("Dialog_ImageSave", "Components:"))
        self.checkBox_YUV.setText(_translate("Dialog_ImageSave", "YUV"))
        self.checkBox_Y.setText(_translate("Dialog_ImageSave", "Y"))
        self.checkBox_UV.setText(_translate("Dialog_ImageSave", "UV"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog_ImageSave", "YUV"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog_ImageSave", "CODED"))
        self.label_14.setText(_translate("Dialog_ImageSave", "Filename:"))

