# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GuiLib/YUView.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_YUView(object):
    def setupUi(self, YUView):
        YUView.setObjectName("YUView")
        YUView.resize(1262, 627)
        self.centralwidget = QtWidgets.QWidget(YUView)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_BufferInfo = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_BufferInfo.setObjectName("groupBox_BufferInfo")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_BufferInfo)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_BufferInfo)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.spinBox_BufferP = QtWidgets.QSpinBox(self.groupBox_BufferInfo)
        self.spinBox_BufferP.setMaximum(8192)
        self.spinBox_BufferP.setProperty("value", 1920)
        self.spinBox_BufferP.setObjectName("spinBox_BufferP")
        self.gridLayout_2.addWidget(self.spinBox_BufferP, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_BufferInfo)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 2, 1, 1)
        self.spinBox_BufferH = QtWidgets.QSpinBox(self.groupBox_BufferInfo)
        self.spinBox_BufferH.setMaximum(8192)
        self.spinBox_BufferH.setProperty("value", 1080)
        self.spinBox_BufferH.setObjectName("spinBox_BufferH")
        self.gridLayout_2.addWidget(self.spinBox_BufferH, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_BufferInfo)
        self.groupBox_ImageInfo = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_ImageInfo.setObjectName("groupBox_ImageInfo")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_ImageInfo)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.groupBox_ImageInfo)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.spinBox_OffsetX = QtWidgets.QSpinBox(self.groupBox_ImageInfo)
        self.spinBox_OffsetX.setMaximum(8192)
        self.spinBox_OffsetX.setObjectName("spinBox_OffsetX")
        self.gridLayout.addWidget(self.spinBox_OffsetX, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_ImageInfo)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 2, 1, 1)
        self.spinBox_OffsetY = QtWidgets.QSpinBox(self.groupBox_ImageInfo)
        self.spinBox_OffsetY.setMaximum(8192)
        self.spinBox_OffsetY.setObjectName("spinBox_OffsetY")
        self.gridLayout.addWidget(self.spinBox_OffsetY, 0, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_ImageInfo)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.spinBox_ImageW = QtWidgets.QSpinBox(self.groupBox_ImageInfo)
        self.spinBox_ImageW.setMaximum(8192)
        self.spinBox_ImageW.setObjectName("spinBox_ImageW")
        self.gridLayout.addWidget(self.spinBox_ImageW, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_ImageInfo)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 2, 1, 1)
        self.spinBox_ImageH = QtWidgets.QSpinBox(self.groupBox_ImageInfo)
        self.spinBox_ImageH.setMaximum(8192)
        self.spinBox_ImageH.setObjectName("spinBox_ImageH")
        self.gridLayout.addWidget(self.spinBox_ImageH, 1, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_ImageInfo)
        self.groupBox_ImageInfo_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_ImageInfo_2.setObjectName("groupBox_ImageInfo_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_ImageInfo_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_SetPixel_2 = QtWidgets.QPushButton(self.groupBox_ImageInfo_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SetPixel_2.sizePolicy().hasHeightForWidth())
        self.pushButton_SetPixel_2.setSizePolicy(sizePolicy)
        self.pushButton_SetPixel_2.setObjectName("pushButton_SetPixel_2")
        self.gridLayout_3.addWidget(self.pushButton_SetPixel_2, 2, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_ImageInfo_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_ImageInfo_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 2, 1, 1)
        self.spinBox_U = QtWidgets.QSpinBox(self.groupBox_ImageInfo_2)
        self.spinBox_U.setMaximum(255)
        self.spinBox_U.setSingleStep(0)
        self.spinBox_U.setObjectName("spinBox_U")
        self.gridLayout_3.addWidget(self.spinBox_U, 1, 3, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_ImageInfo_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 1, 4, 1, 1)
        self.spinBox_PixelX = QtWidgets.QSpinBox(self.groupBox_ImageInfo_2)
        self.spinBox_PixelX.setMaximum(8192)
        self.spinBox_PixelX.setObjectName("spinBox_PixelX")
        self.gridLayout_3.addWidget(self.spinBox_PixelX, 0, 1, 1, 1)
        self.spinBox_V = QtWidgets.QSpinBox(self.groupBox_ImageInfo_2)
        self.spinBox_V.setMaximum(255)
        self.spinBox_V.setObjectName("spinBox_V")
        self.gridLayout_3.addWidget(self.spinBox_V, 1, 5, 1, 1)
        self.pushButton_SetPixel = QtWidgets.QPushButton(self.groupBox_ImageInfo_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SetPixel.sizePolicy().hasHeightForWidth())
        self.pushButton_SetPixel.setSizePolicy(sizePolicy)
        self.pushButton_SetPixel.setObjectName("pushButton_SetPixel")
        self.gridLayout_3.addWidget(self.pushButton_SetPixel, 2, 5, 1, 1)
        self.spinBox_PixelY = QtWidgets.QSpinBox(self.groupBox_ImageInfo_2)
        self.spinBox_PixelY.setMaximum(8192)
        self.spinBox_PixelY.setObjectName("spinBox_PixelY")
        self.gridLayout_3.addWidget(self.spinBox_PixelY, 0, 3, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_ImageInfo_2)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 1, 2, 1, 1)
        self.spinBox_Y = QtWidgets.QSpinBox(self.groupBox_ImageInfo_2)
        self.spinBox_Y.setMaximum(255)
        self.spinBox_Y.setObjectName("spinBox_Y")
        self.gridLayout_3.addWidget(self.spinBox_Y, 1, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_ImageInfo_2)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 1, 0, 1, 1)
        self.widget_Color = ColorWidget(self.groupBox_ImageInfo_2)
        self.widget_Color.setObjectName("widget_Color")
        self.gridLayout_3.addWidget(self.widget_Color, 0, 5, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_ImageInfo_2)
        spacerItem = QtWidgets.QSpacerItem(20, 128, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_6.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.tab)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.listWidget_CFA = QtWidgets.QListWidget(self.splitter)
        self.listWidget_CFA.setObjectName("listWidget_CFA")
        self.groupBox_ImageInfo_3 = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_ImageInfo_3.setObjectName("groupBox_ImageInfo_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_ImageInfo_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_19 = QtWidgets.QLabel(self.groupBox_ImageInfo_3)
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 0, 0, 1, 1)
        self.comboBox_Compo_4 = QtWidgets.QComboBox(self.groupBox_ImageInfo_3)
        self.comboBox_Compo_4.setObjectName("comboBox_Compo_4")
        self.comboBox_Compo_4.addItem("")
        self.comboBox_Compo_4.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_Compo_4, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_ImageInfo_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 1, 0, 1, 1)
        self.comboBox_Compo_3 = QtWidgets.QComboBox(self.groupBox_ImageInfo_3)
        self.comboBox_Compo_3.setObjectName("comboBox_Compo_3")
        self.comboBox_Compo_3.addItem("")
        self.comboBox_Compo_3.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_Compo_3, 1, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.splitter)
        self.widget_MonitorCFA = MonitorWidget(self.tab)
        self.widget_MonitorCFA.setObjectName("widget_MonitorCFA")
        self.horizontalLayout_2.addWidget(self.widget_MonitorCFA)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 4)
        self.gridLayout_7.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter_2 = QtWidgets.QSplitter(self.tab_2)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.listWidget_YUV = QtWidgets.QListWidget(self.splitter_2)
        self.listWidget_YUV.setObjectName("listWidget_YUV")
        self.groupBox_ImageInfo_4 = QtWidgets.QGroupBox(self.splitter_2)
        self.groupBox_ImageInfo_4.setObjectName("groupBox_ImageInfo_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_ImageInfo_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_20 = QtWidgets.QLabel(self.groupBox_ImageInfo_4)
        self.label_20.setObjectName("label_20")
        self.gridLayout_8.addWidget(self.label_20, 0, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_ImageInfo_4)
        self.label_21.setObjectName("label_21")
        self.gridLayout_8.addWidget(self.label_21, 1, 0, 1, 1)
        self.comboBox_Compo_8 = QtWidgets.QComboBox(self.groupBox_ImageInfo_4)
        self.comboBox_Compo_8.setObjectName("comboBox_Compo_8")
        self.comboBox_Compo_8.addItem("")
        self.comboBox_Compo_8.addItem("")
        self.comboBox_Compo_8.addItem("")
        self.comboBox_Compo_8.addItem("")
        self.comboBox_Compo_8.addItem("")
        self.comboBox_Compo_8.addItem("")
        self.gridLayout_8.addWidget(self.comboBox_Compo_8, 0, 1, 1, 1)
        self.comboBox_Compo_2 = QtWidgets.QComboBox(self.groupBox_ImageInfo_4)
        self.comboBox_Compo_2.setObjectName("comboBox_Compo_2")
        self.comboBox_Compo_2.addItem("")
        self.comboBox_Compo_2.addItem("")
        self.comboBox_Compo_2.addItem("")
        self.comboBox_Compo_2.addItem("")
        self.gridLayout_8.addWidget(self.comboBox_Compo_2, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.splitter_2)
        self.widget_MonitorCFA_2 = MonitorWidget(self.tab_2)
        self.widget_MonitorCFA_2.setObjectName("widget_MonitorCFA_2")
        self.horizontalLayout.addWidget(self.widget_MonitorCFA_2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 4)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_6.addWidget(self.tabWidget, 0, 0, 1, 1)
        YUView.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(YUView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1262, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        YUView.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(YUView)
        self.statusbar.setObjectName("statusbar")
        YUView.setStatusBar(self.statusbar)
        self.action_OpenFile = QtWidgets.QAction(YUView)
        self.action_OpenFile.setObjectName("action_OpenFile")
        self.action_Save = QtWidgets.QAction(YUView)
        self.action_Save.setObjectName("action_Save")
        self.menuFile.addAction(self.action_OpenFile)
        self.menuFile.addAction(self.action_Save)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(YUView)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(YUView)

    def retranslateUi(self, YUView):
        _translate = QtCore.QCoreApplication.translate
        YUView.setWindowTitle(_translate("YUView", "YUView"))
        self.groupBox_BufferInfo.setTitle(_translate("YUView", "Buffer Info"))
        self.label_4.setText(_translate("YUView", "Pitch"))
        self.label_5.setText(_translate("YUView", "Height"))
        self.groupBox_ImageInfo.setTitle(_translate("YUView", "Image Info"))
        self.label_8.setText(_translate("YUView", "x offset:"))
        self.label_9.setText(_translate("YUView", "Y Offset:"))
        self.label_10.setText(_translate("YUView", "Width:"))
        self.label_11.setText(_translate("YUView", "Heigth:"))
        self.groupBox_ImageInfo_2.setTitle(_translate("YUView", "Pixel Info"))
        self.pushButton_SetPixel_2.setText(_translate("YUView", "More"))
        self.label_12.setText(_translate("YUView", "x:"))
        self.label_13.setText(_translate("YUView", "Y:"))
        self.label_24.setText(_translate("YUView", "V:"))
        self.pushButton_SetPixel.setText(_translate("YUView", "Set"))
        self.label_25.setText(_translate("YUView", "U:"))
        self.label_26.setText(_translate("YUView", "Y:"))
        self.groupBox_ImageInfo_3.setTitle(_translate("YUView", "CFA Info"))
        self.label_19.setText(_translate("YUView", "Pattern"))
        self.comboBox_Compo_4.setItemText(0, _translate("YUView", "RGGB"))
        self.comboBox_Compo_4.setItemText(1, _translate("YUView", "GRBG"))
        self.label_18.setText(_translate("YUView", "Demosaic"))
        self.comboBox_Compo_3.setItemText(0, _translate("YUView", "Bylinear"))
        self.comboBox_Compo_3.setItemText(1, _translate("YUView", "DDFAPD"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("YUView", "CFA"))
        self.groupBox_ImageInfo_4.setTitle(_translate("YUView", "CFA Info"))
        self.label_20.setText(_translate("YUView", "Pattern"))
        self.label_21.setText(_translate("YUView", "Demosaic"))
        self.comboBox_Compo_8.setItemText(0, _translate("YUView", "IYUV"))
        self.comboBox_Compo_8.setItemText(1, _translate("YUView", "YV12"))
        self.comboBox_Compo_8.setItemText(2, _translate("YUView", "NV12"))
        self.comboBox_Compo_8.setItemText(3, _translate("YUView", "YU16"))
        self.comboBox_Compo_8.setItemText(4, _translate("YUView", "YV16"))
        self.comboBox_Compo_8.setItemText(5, _translate("YUView", "NV16"))
        self.comboBox_Compo_2.setItemText(0, _translate("YUView", "Y\'Cb\'Cr"))
        self.comboBox_Compo_2.setItemText(1, _translate("YUView", "Y only"))
        self.comboBox_Compo_2.setItemText(2, _translate("YUView", "Cb only"))
        self.comboBox_Compo_2.setItemText(3, _translate("YUView", "Cr only"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("YUView", "YUV"))
        self.menuFile.setTitle(_translate("YUView", "File"))
        self.action_OpenFile.setText(_translate("YUView", "Open"))
        self.action_Save.setText(_translate("YUView", "Save"))

from CustomWidget import ColorWidget, MonitorWidget
